Feature
andrikeev/Synoptic pull request #5
Opened 2017-07-27 08:55 UTC by 0v3rt1r3d

Added: city entering with suggestions

2017-07-28 10:00 UTC, andrikeev requested changes
В целом ок.
Есть вопрос по получению погоды, мне кажется лучше хранить координаты, но на твоё усмотрение.
И с адаптером что-то придумай, каждый раз новый создавать это не ок и вынеси в отдельный класс обязательно

2017-07-28 10:00 UTC, andrikeev commented on app/src/main/java/ru/andrikeev/android/synoptic/model/network/google_places/GooglePlacesApi.java
> +import ru.andrikeev.android.synoptic.model.network.google_places.response_places.PlacesResponse;
`google_places` - сделай просто places или googleplaces , в Java названия пакетов принято одним словом писать, без разделителей
и `response_places` тоже

2017-07-28 10:00 UTC, andrikeev commented on app/src/main/java/ru/andrikeev/android/synoptic/model/network/openweather/OpenWeatherApi.java
> +import ru.andrikeev.android.synoptic.model.network.openweather.response_place.response.WeatherResponse;
Тоже

2017-07-28 10:00 UTC, andrikeev commented on app/src/main/java/ru/andrikeev/android/synoptic/presentation/presenter/city/CityPresenter.java
> +    Settings settings;
Модификаторы доступа

2017-07-28 10:00 UTC, andrikeev commented on app/src/main/java/ru/andrikeev/android/synoptic/application/Settings.java
> +    public long getCityId(){
Может лучше хранить координаты и по ним запрашивать, а не по id?

2017-07-28 10:00 UTC, andrikeev commented on app/src/main/java/ru/andrikeev/android/synoptic/presentation/presenter/city/CityPresenter.java
> +        placesService.loadPlace(placeId)
`subscription =`, иначе может быть утечка

2017-07-28 10:00 UTC, andrikeev commented on app/src/main/java/ru/andrikeev/android/synoptic/presentation/presenter/city/CityPresenter.java
> +                .map(new Function<PlacesResponse, Location>() {
Это должно быть не в презенте а в модели

2017-07-28 10:00 UTC, andrikeev commented on app/src/main/java/ru/andrikeev/android/synoptic/presentation/presenter/city/CityPresenter.java
> +                            getViewState().updateList(ResponceConverter.toViewModel(predictionsResponse));
Response*
Это должно быть в модели

2017-07-28 10:00 UTC, andrikeev commented on app/src/main/java/ru/andrikeev/android/synoptic/presentation/presenter/city/CityPresenter.java
> +                        weatherService.loadWeather(location.getLatitude(), location.getLongitude())
Вот это мне кажется лишнее, можно же на openweather просто по координатам получать. У них написано конечно, что лучше использовать id, но это просто рекомендация

2017-07-28 10:00 UTC, andrikeev commented on app/src/main/java/ru/andrikeev/android/synoptic/ui/fragment/city/CityFragment.java
> +        recyclerView.setAdapter(new CityAdapter(cities));
Лучше сделать один адаптер в `onCreate()` и у него методы `clear()` и `add(List<PredictionModel> cities)`

2017-07-28 10:00 UTC, andrikeev commented on app/src/main/java/ru/andrikeev/android/synoptic/ui/fragment/city/CityFragment.java
> +        Toast.makeText(getActivity(), "Error", Toast.LENGTH_SHORT).show(); // TODO: show error
А чего не сделал? )

2017-07-28 10:00 UTC, andrikeev commented on app/src/main/java/ru/andrikeev/android/synoptic/ui/fragment/city/CityFragment.java
> +    private class CityAdapter extends RecyclerView.Adapter<CityHolder>{
В отдельный класс

2017-07-28 10:00 UTC, andrikeev commented on app/src/main/java/ru/andrikeev/android/synoptic/ui/fragment/city/CityFragment.java
> +    private class CityHolder extends RecyclerView.ViewHolder implements View.OnClickListener {
В класс адаптера

2017-07-28 14:36 UTC, andrikeev requested changes

2017-07-28 14:36 UTC, andrikeev commented on app/src/main/java/ru/andrikeev/android/synoptic/model/CityResolver.java
> +    public Single<List<PredictionModel>> loadPredictions(@NonNull String input){
`Prediction` это наверное всё таки не то, тут скорее `Suggestion`

2017-07-28 14:36 UTC, andrikeev commented on app/src/main/java/ru/andrikeev/android/synoptic/model/CityResolver.java
> +import io.reactivex.annotations.NonNull;
Поменяй на `android.support.annotation.NonNull`

2017-07-28 14:36 UTC, andrikeev commented on app/src/main/java/ru/andrikeev/android/synoptic/model/CityResolver.java
> +                        if(placesResponse.getResultPlace()!=null) {
Здесь, наверное, лучше код/статус ответа проверять

2017-07-28 14:36 UTC, andrikeev commented on app/src/main/java/ru/andrikeev/android/synoptic/ui/fragment/city/CityAdapter.java
> +    public CityAdapter(Context context, CityPresenter presenter){
Презентер нельзя передавать сюда, передавай интерфейс `OnCityClickedListener` какой-нибудь, имлементируй его фрагментом, и в методе `onCityClicked(Prediction model)` вызывай `presenter.onCityClicked(Prediction model)`

2017-07-28 14:36 UTC, andrikeev commented on app/src/main/java/ru/andrikeev/android/synoptic/ui/fragment/city/CityAdapter.java
> +    public CityAdapter(Context context, CityPresenter presenter){
`Context` тут тоже не нужен

2017-07-28 14:36 UTC, andrikeev commented on app/src/main/java/ru/andrikeev/android/synoptic/ui/fragment/city/CityAdapter.java
> +        LayoutInflater inflater = LayoutInflater.from(context);
`LayoutInflater.from(parent.getContext()).inflate(..)`

2017-07-28 14:36 UTC, andrikeev commented on app/src/main/java/ru/andrikeev/android/synoptic/ui/fragment/city/CityFragment.java
> +        adapter.notifyItemRangeChanged(0,cities.size());
notify вызывать лучше внутри адаптера

2017-07-28 14:36 UTC, andrikeev commented on app/src/main/java/ru/andrikeev/android/synoptic/ui/fragment/city/CityFragment.java
> +                }).subscribe(presenter.getConsumer());
Помоем тут тоже не очень хорошо. Я на лекции как раз спрашивал как лучше в этом случае делать, и мне первый вариант понравился больше - в презенте передаётся `Observable` на изменения и подписка уже внутри него происходит. Типа какой-нибудь метод `CityPresenter::onTextChanged(Observable<CharSequence> textChangedObservable)`

2017-07-29 13:27 UTC, andrikeev approved these changes

2017-07-29 13:29 UTC, andrikeev commented
Ну там небольшие замечания ещё, но в целом можно вливать, только конфликты разреши

2017-07-30 08:36 UTC, andrikeev commented on app/src/main/java/ru/andrikeev/android/synoptic/model/network/googleplaces/places/Result.java
> +    private String address;
А это поле вообще нужно?

2017-07-30 08:38 UTC, 0v3rt1r3d commented on app/src/main/java/ru/andrikeev/android/synoptic/model/network/googleplaces/places/Result.java
> +    private String address;
Да, оно потом переходит в name в другом объекте и показывает название города

2017-07-30 10:55 UTC, closed without merging